#' Apply a Discretized OLS model to logistic time series data
#'
#' An Euler discretization of the logistic growth ODE problem is used to
#' formulate the problem as an Ordinary Least Squares regression problem. So,
#' OLS is used to estimate the value of the logistic growth parameters, r, and
#' optionally K if the model has not been normalized.
#'
#' Applying Tikhonov regularization (AKA "Ridge regression") is also supported
#' by specifying the value of the smoothing constant. Options are provided to
#' print a plot of linearized data and print the results to the console.
#'
#' @param df A data frame; typically generated by generate_data_frame(). One
#'     column should be named "t" and numeric, and the second column should be
#'     named "P" and numeric.
#' @param smoothing Nonnegative numeric; if >0 applies Tikhonov regularization
#'     to the OLS model where this value is lambda. For our purposes, this
#'     essentially forces the estimations to be smaller.
#' @param dimensionless Logical; if TRUE, the model is assumed to have one
#'     parameter, r, which is estimated. If FALSE, the model is assumed to have
#'     two parameters, r and K, which are estimated.
#' @param make_plot Logical; if TRUE, prints a plot of the linearized data.
#' @param print_res Logical; if TRUE, the values of the estimated parameters
#'     are printed to the console.
#'
#' @return A named numeric vector of parameters which were estimated.
#' @export
#'
#' @examples
model_logistic_data <- function(df, smoothing = 0, dimensionless = TRUE,
                                make_plot = FALSE, print_res = FALSE) {
  # This function uses a derived least-squares method with an Euler
  #  discretization in order to solve for the parameter(s) of the logistic
  #  equation modeling the inputted data.

  # Validate inputs. Don't run if they are bad.
  if (!is.data.frame(df)) {
    stop("df should be a data frame generated by generate_logistic_data().")
  }
  if (smoothing < 0 | !is.numeric(smoothing)) {
    stop("smoothing parameter should be a nonnegative numeric value.")
  }
  if (!is.logical(dimensionless)) {
    stop("dimensionless specification must be either TRUE or FALSE.")
  }
  if (!is.logical(make_plot)) {
    stop("make_plot specification must be either TRUE or FALSE.")
  }
  if (!is.logical(print_res)) {
    stop("print_res specification must be either TRUE or FALSE.")
  }

  # Set up data: get P forward, P present, time step.
  # Extract P and t so I don't have to use $ every time.
  P <- df$P
  t <- df$t
  # Now calculate necessary model components.
  P_forward <- P[2:max(t)]
  P_present <- P[1:(max(t) - 1)]
  if (is.null(ts)) {
    # Assume time step goes from 0:max(t) by evenly spaced intervals.
    ts <- max(t) / length(t)
  }

  # Check if model is dimensionless or not, and calculate most of the model.
  # First, calculate b vector since it is the same either way.
  b <- (1/time_step)*log(P_forward/P_present)

  # Generate matrix A for model. Different based on number of parameters.
  if (dimensionless) {
    A <- 1 - P_present
  } else {
    b <- (1/time_step)*log(P_forward/P_present)
    A <- cbind(rep(1, length(P_present)), -P_present)
  }

  ATA <- t(A) %*% A # Matrix multiply A^T with A.

  # Apply smoothing if requested.
  if (smoothing == 0) {
    params <- MASS::ginv(ATA) %*% t(A) %*% b
  } else {
    ID <- diag(nrow(ATA))
    params <- MASS::ginv(ATA + smoothing_value * ID) %*% t(A) %*% b
  }

  # Collect outputs.
  if (dimensionless) {
    r_hat <- params[1]
    output_params <- unlist(
      list("r" = as.numeric(r_hat))
    )
  } else {
    r_hat <- params[1]
    m_hat <- params[2]
    K_hat <- (r_hat/m_hat)
    output_params <- unlist(
      list("r" = as.numeric(r_hat),
           "K" = as.numeric(K_hat))
    )
  }

  # Print results and/or make plot.
  if (make_plot == TRUE) {
    plot(1 - P_present, b)
  }

  if (print_res == TRUE) {
    if (dimensionless) {
      cat("The estimated growth rate is:", r_hat,"\n")
    } else {
      cat("The estimated growth rate is:", r_hat,
          "\nThe estimated carrying capacity is:", K_hat, "\n")
    }
  }

  # Return outputs.
  return(output_params)
}
